### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by perrette** [perrette/dimarray#24]
I'd like to have a clearer, shorter / better organized documentation.
My first idea, when I started the dimarray.ipynb notebook, was to convert the notebook to a documentation somehow, but it did not quite work (conversion to rst etc...) and a big documentation notebook with everything is not very user-friendly. Another problem is that some of the examples are not very useful and actually intended as tests. 

Here is what I think could work to make a big improvement:
- use sphinx and possibly numpydoc to organize a nice rst / html documentation in a `doc` directory, and creating a gh-pages branch. Here are [some interesting guidelines](http://raxcloud.blogspot.de/2013/02/documenting-python-code-using-sphinx.html) to combine sphinx and github (for formatting use `numpydoc`, see below). This is similar to this [2-directory solution](http://daler.github.io/sphinxdoc-test/includeme.html) but using `git-new-dir` utility to handle several branches in separate folders of a single git repository. Rules for ReStructuredTxt can be found in various places: [here](http://sphinx-doc.org/markup/toctree.html), [here](http://docutils.sourceforge.net/docs/user/rst/cheatsheet.txt) and [there](http://docutils.sourceforge.net/docs/user/rst/quickref.html) or [there](http://codeandchaos.wordpress.com/2012/07/30/sphinx-autodoc-tutorial-for-dummies/).
- Use [numpydoc extention](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) to sphinx, which looks better than native sphinx :params: and :returns: keyword, and is already compatible with existing dimarray docstrings.
- have an `examples` folder with notebook examples that can be converted to rst and then html. There seems to be ways with ipython, e.g. [this issue](https://github.com/ipython/ipython/issues/4936) or [that one](https://github.com/ipython/nbconvert/issues/54), or this [discussion](http://python.6.x6.nabble.com/IPython-User-usage-of-notebooks-in-sphinx-td5041731.html)
- Thin down examples in docstring to the essential. Move the rest as tests using py.test (see Issue #7), with a separate `tests` folder.

@vnoel Do you have any experience with that / a better idea of the path to follow?

**Comment by mgeier** [comment]
You might be interested in my Sphinx extension [nbsphinx](http://nbsphinx.readthedocs.org/).

It can run the notebooks on readthedocs.org without the intermediate conversion to reST (which is done internally by the extension).

It is still work-in-progress and it might still have a few rough corners, but I think it might be worth a try!

And if anything is missing, feel free to contribute: https://github.com/spatialaudio/nbsphinx/!

**Comment by perrette** [comment]
@mgeier : sounds good, I will take a look next time I do significant development on dimarray. Thanks.
