### ISSUE TITLE
dimension are not taken up properly by from_pandas

### ISSUE THREAD

**Issue by matthiasmengel** [perrette/dimarray#35]
try this little example:

```
import pandas as pd
import dimarray as da
df = pd.DataFrame(np.random.rand(5,2),columns=["bla","blub"])
df.index.name = "YEARS"
print df
## chooses names x1, ok!
print da.from_pandas(df)
## uses "t" instead of "time", bug!
print da.from_pandas(df,dims="time")
```
the dimension name "time" in the last line is not used. instead, it is shortened to "t". I think that should not be.
```da.__version__ = 0.1.9.dev```

**Comment by perrette** [comment]
That is because `dims` expects a sequence, and list("time") = ["t", "i", ...]. Try:

    print da.from_pandas(df,dims=["time", "x"])

It should definitely throw an error instead of silently converting the string.
I use latest pip version 0.2.3  ;-)
